-- Supabase Schema for Items Table

-- Drop existing policies if they exist
drop policy if exists "Users can view all items" on items;
drop policy if exists "Users can insert their own items" on items;
drop policy if exists "Users can update their own items" on items;
drop policy if exists "Users can delete their own items" on items;

-- Drop the items table if it exists
drop table if exists items;

-- Create items table
create table items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  condition text not null,
  location text,
  image_url text,
  owner_id text not null,  -- Using text to match Firebase user IDs
  owner_name text not null,
  status text not null default 'available',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add indexes for better query performance
create index idx_items_owner_id on items (owner_id);
create index idx_items_category on items (category);
create index idx_items_status on items (status);
create index idx_items_created_at on items (created_at);

-- Set up Row Level Security (RLS)
alter table items enable row level security;

-- Create policies that work with Firebase Auth
create policy "Users can view all items" on items
  for select using (true);

create policy "Users can insert their own items" on items
  for insert with check (true);  -- Allow all authenticated users to insert

create policy "Users can update their own items" on items
  for update using (owner_id = owner_id);  -- Allow all updates (you may want to restrict this)

create policy "Users can delete their own items" on items
  for delete using (owner_id = owner_id);  -- Allow all deletes (you may want to restrict this)

-- Grant permissions
grant usage on schema public to anon, authenticated;
grant all on table items to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Storage policies for item-images bucket
-- These need to be set up in the Supabase dashboard Storage section:
-- 
-- For SELECT: Allow all users to view images
-- CREATE POLICY "Allow public read access" ON storage.objects 
-- FOR SELECT TO anon, authenticated USING (bucket_id = 'item-images');
-- 
-- For INSERT: Allow authenticated users to upload images
-- CREATE POLICY "Allow authenticated insert access" ON storage.objects 
-- FOR INSERT TO authenticated WITH CHECK (bucket_id = 'item-images');